# This is a basic workflow that is manually triggered

name: Manual publish

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Publish PowerShell Module
      # You may pin to the exact commit or the version.

      uses: chenxizhang/publish-powershell-module-action@v19
      with:
        # The NuGet API Key for PowerShell Gallery, with permission to push this module.
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
